### ISSUE TITLE
CORS Issue In Firefox

### ISSUE THREAD

**Issue by wgmyers** [SuffolkLITLab/rss_algo#9]
Does not work in Firefox (113.0.2) due to CORS issues.

Each feed gets an error message in the console like the following:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tools.suffolklitlab.org/rss_proxy/?url=https%3A%2F%2Fclarkesworldmagazine.com%2Ffeed%2F. (Reason: CORS request did not succeed). Status code: (null).`

**Comment by colarusso** [comment]
Haven’t been able to replicate this issue.
